(function(){
'use strict';
const $=id=>document.getElementById(id);
const moeda=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const data=v=>{const d=new Date(v||'');return Number.isNaN(d.getTime())?'—':d.toLocaleString('pt-BR')};
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const classe=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9_-]/g,'-');
let alvoCredito=null,alvoAssinatura=null,ultimoFoco=null,seq=0,timerToast=null;

function notificar(msg,tipo='sucesso'){
 const toast=$('admin-toast'),status=$('admin-status');
 if(!toast||!status)return;
 clearTimeout(timerToast);toast.textContent=msg;status.textContent=msg;
 toast.classList.toggle('erro',tipo==='erro');toast.classList.add('ativo');
 timerToast=setTimeout(()=>toast.classList.remove('ativo'),4200);
}
function badge(v){const t=v||'—';return `<span class="badge ${classe(t)}">${esc(t)}</span>`}
function tabela(vazia,cab,linhas){return linhas.length?`<table class="table"><thead><tr>${cab.map(x=>`<th scope="col">${esc(x)}</th>`).join('')}</tr></thead><tbody>${linhas.join('')}</tbody></table>`:`<div class="empty">${esc(vazia)}</div>`}
function botao(acao,dados,texto,tipo='alt'){const attrs=Object.entries(dados).map(([k,v])=>`data-${k}="${esc(v)}"`).join(' ');return `<button class="btn ${tipo}" type="button" data-admin-action="${esc(acao)}" ${attrs}>${esc(texto)}</button>`}
function renderResumo(r={}){$('admin-metricas').innerHTML=[['Usuários',r.usuarios_total||0],['Assinaturas ativas',r.assinaturas_ativas||0],['Receita total',moeda(r.receita_total)],['Pix pendentes',r.pagamentos_pendentes||0],['Essencial',r.essencial_ativos||0],['PRO',r.pro_ativos||0],['Créditos em circulação',r.creditos_em_circulacao||0]].map(([l,v])=>`<article class="card metric"><span>${esc(l)}</span><strong>${esc(v)}</strong></article>`).join('')}
function renderUsuarios(lista=[]){$('lista-usuarios').innerHTML=tabela('Nenhum usuário encontrado.',['Usuário','Empresa','Plano','Status','Saldo Efex','Cadastro','Último acesso','Ações'],lista.map(u=>{const nome=u.nome||u.email||'Usuário',nivel=u.nivel||u.plano||'gratis',status=u.status||'ativo',saldo=Number(u.saldo_efex||0);return `<tr><td><strong>${esc(nome)}</strong><br><small>${esc(u.email||'')}</small></td><td>${esc(u.nome_empresa||'—')}</td><td>${esc(nivel)}</td><td>${badge(status)}</td><td><strong>${saldo}</strong></td><td>${data(u.criado_em)}</td><td>${data(u.last_sign_in_at)}</td><td><div class="row-actions">${botao('creditos',{'usuario-id':u.id,nome,saldo},'Créditos','gold')}${botao('assinatura',{'usuario-id':u.id,nome,nivel,status},'Assinatura')}</div></td></tr>`}))}
function renderAssinaturas(lista=[]){$('lista-assinaturas').innerHTML=tabela('Nenhuma assinatura encontrada.',['Usuário','Empresa','Nível','Status','Créditos/mês','Expiração','Ações'],lista.map(a=>{const nome=a.nome||a.email||'Usuário',nivel=a.nivel||a.plano||'gratis',status=a.status||'ativo';return `<tr><td><strong>${esc(nome)}</strong><br><small>${esc(a.email||'')}</small></td><td>${esc(a.nome_empresa||'—')}</td><td>${esc(nivel)}</td><td>${badge(status)}</td><td>${Number(a.creditos_mensais||0)}</td><td>${data(a.expira_em)}</td><td>${botao('assinatura',{'usuario-id':a.usuario_id,nome,nivel,status},'Gerenciar')}</td></tr>`}))}
function produto(p){if(p.produto_codigo==='assinatura_essencial')return'Premium Essencial';if(p.produto_codigo==='assinatura_pro')return'Premium PRO';if(String(p.produto_codigo||'').startsWith('creditos_'))return`${p.creditos||''} créditos Efex`;return p.produto_codigo||p.produto_tipo||'Pagamento'}
function renderPagamentos(lista=[]){$('lista-pagamentos').innerHTML=tabela('Nenhum pagamento encontrado.',['Data','Usuário','Produto','Valor','Status','Pago em','Aplicado'],lista.map(p=>`<tr><td>${data(p.criado_em)}</td><td><strong>${esc(p.nome||p.email||'—')}</strong><br><small>${esc(p.email||'')}</small></td><td>${esc(produto(p))}</td><td><strong>${moeda(p.valor)}</strong></td><td>${badge(p.status)}</td><td>${data(p.pago_em)}</td><td>${p.aplicado_em?'Sim':'Não'}</td></tr>`))}
function renderAuditoria(lista=[]){$('lista-auditoria').innerHTML=tabela('Nenhuma ação administrativa registrada.',['Data','Administrador','Ação','Entidade','Motivo'],lista.map(a=>`<tr><td>${data(a.criado_em)}</td><td>${esc(a.admin_email||a.admin_usuario_id||'—')}</td><td>${esc(a.acao||'—')}</td><td>${esc(a.entidade_tipo||'—')}<br><small>${esc(a.entidade_id||'')}</small></td><td>${esc(a.motivo||'—')}</td></tr>`))}
function carregando(ativo){$('admin-app')?.setAttribute('aria-busy',String(ativo));const b=$('admin-buscar');if(b){b.disabled=ativo;b.textContent=ativo?'Buscando...':'Buscar'}}
function negar(){const app=$('admin-app');if(!app)return;app.setAttribute('aria-busy','false');app.innerHTML='<section class="card hero"><h1>Acesso não autorizado</h1><p>Esta área é exclusiva da equipe administrativa do FS Orçamentos.</p><p style="margin-top:16px"><a class="btn alt" href="/dashboard.html">Voltar ao painel</a></p></section>'}
async function carregar(){const atual=++seq;carregando(true);try{if(!window._supabase?.auth)throw new Error('Não foi possível inicializar a conexão segura.');const{data:auth,error:authError}=await _supabase.auth.getSession();if(authError)throw authError;if(!auth?.session?.user?.id){location.replace('/index.html?login=1&dest='+encodeURIComponent('/admin.html'));return}const busca=$('admin-busca')?.value.trim().slice(0,120)||'';const{data:r,error}=await _supabase.rpc('fs_admin_painel_essencial',{p_busca:busca||null,p_limite:50,p_offset:0});if(atual!==seq)return;if(error){console.error('Falha ao carregar painel administrativo:',error);negar();return}renderResumo(r?.resumo);renderUsuarios(r?.usuarios||[]);renderAssinaturas(r?.assinaturas||[]);renderPagamentos(r?.pagamentos||[]);renderAuditoria(r?.auditoria||[]);if(busca)notificar('Busca concluída.')}catch(e){console.error(e);notificar(e?.message||'Não foi possível carregar o painel.','erro')}finally{if(atual===seq)carregando(false)}}
function abrirModal(m){if(!m)return;ultimoFoco=document.activeElement;m.classList.add('ativo');m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';requestAnimationFrame(()=>m.querySelector('.modal-box')?.focus())}
function fecharModal(m){if(!m)return;m.classList.remove('ativo');m.setAttribute('aria-hidden','true');document.body.style.overflow='';ultimoFoco?.focus?.();ultimoFoco=null}
function abrirCredito(id,nome,saldo){if(!id)return;alvoCredito=id;$('credito-usuario').textContent=`${nome} • saldo atual: ${saldo}`;$('credito-delta').value='';$('credito-motivo').value='';abrirModal($('modal-creditos'));requestAnimationFrame(()=>$('credito-delta')?.focus())}
function fecharCredito(){fecharModal($('modal-creditos'));alvoCredito=null}
async function ajustarCredito(){const delta=Number($('credito-delta').value),motivo=$('credito-motivo').value.trim();if(!alvoCredito||!Number.isInteger(delta)||delta===0){notificar('Informe uma quantidade inteira diferente de zero.','erro');$('credito-delta').focus();return}if(motivo.length<5){notificar('Informe um motivo com pelo menos 5 caracteres.','erro');$('credito-motivo').focus();return}const b=$('credito-confirmar');b.disabled=true;b.textContent='Aplicando...';try{const{data:r,error}=await _supabase.rpc('fs_admin_ajustar_creditos',{p_usuario_id:alvoCredito,p_delta:delta,p_motivo:motivo});if(error||!r?.sucesso)throw new Error(error?.message||'Não foi possível ajustar créditos.');fecharCredito();notificar(`Saldo atualizado para ${r.saldo_atual} créditos.`);await carregar()}catch(e){notificar(e.message||'Não foi possível ajustar créditos.','erro')}finally{b.disabled=false;b.textContent='Aplicar ajuste'}}
function ajustarCampos(){const a=$('assinatura-acao').value;$('campo-assinatura-nivel').hidden=!['alterar_nivel','reativar'].includes(a);$('campo-assinatura-dias').hidden=!['adicionar_dias','reativar'].includes(a)}
function abrirAssinatura(id,nome,nivel,status){if(!id)return;alvoAssinatura=id;$('assinatura-usuario').textContent=`${nome} • ${nivel||'grátis'} • ${status||'ativo'}`;$('assinatura-acao').value=['cancelado','expirado'].includes(status)?'reativar':'alterar_nivel';$('assinatura-nivel').value=nivel==='pro'?'pro':'essencial';$('assinatura-dias').value='30';$('assinatura-motivo').value='';ajustarCampos();abrirModal($('modal-assinatura'));requestAnimationFrame(()=>$('assinatura-acao')?.focus())}
function fecharAssinatura(){fecharModal($('modal-assinatura'));alvoAssinatura=null}
async function gerenciarAssinatura(){const acao=$('assinatura-acao').value,nivel=$('assinatura-nivel').value,dias=Number($('assinatura-dias').value),motivo=$('assinatura-motivo').value.trim();if(!alvoAssinatura)return;if(motivo.length<5){notificar('Informe um motivo com pelo menos 5 caracteres.','erro');$('assinatura-motivo').focus();return}if(['adicionar_dias','reativar'].includes(acao)&&(!Number.isInteger(dias)||dias<1||dias>365)){notificar('Informe entre 1 e 365 dias.','erro');$('assinatura-dias').focus();return}if(acao==='cancelar'&&!confirm('Confirma o cancelamento desta assinatura?'))return;const b=$('assinatura-confirmar');b.disabled=true;b.textContent='Aplicando...';try{const{data:r,error}=await _supabase.rpc('fs_admin_gerenciar_assinatura',{p_usuario_id:alvoAssinatura,p_acao:acao,p_nivel:nivel||null,p_dias:Number.isInteger(dias)?dias:null,p_motivo:motivo});if(error||!r?.sucesso)throw new Error(error?.message||'Não foi possível alterar a assinatura.');fecharAssinatura();notificar('Assinatura atualizada com sucesso.');await carregar()}catch(e){notificar(e.message||'Não foi possível alterar a assinatura.','erro')}finally{b.disabled=false;b.textContent='Aplicar alteração'}}
function ativarAba(btn){const nome=btn.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>{const ativo=x===btn;x.classList.toggle('ativo',ativo);x.setAttribute('aria-selected',String(ativo));x.tabIndex=ativo?0:-1});document.querySelectorAll('.painel').forEach(p=>{const ativo=p.id===`painel-${nome}`;p.classList.toggle('ativo',ativo);p.hidden=!ativo})}
function acaoTabela(e){const b=e.target.closest('[data-admin-action]');if(!b)return;const{adminAction,usuarioId,nome,saldo,nivel,status}=b.dataset;if(adminAction==='creditos')abrirCredito(usuarioId,nome,Number(saldo||0));if(adminAction==='assinatura')abrirAssinatura(usuarioId,nome,nivel,status)}
function eventos(){document.querySelectorAll('[data-tab]').forEach(btn=>{btn.addEventListener('click',()=>ativarAba(btn));btn.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;const abas=[...document.querySelectorAll('[data-tab]')],i=abas.indexOf(btn),n=e.key==='ArrowRight'?(i+1)%abas.length:(i-1+abas.length)%abas.length;e.preventDefault();abas[n].focus();ativarAba(abas[n])})});$('admin-buscar')?.addEventListener('click',carregar);$('admin-busca')?.addEventListener('keydown',e=>{if(e.key==='Enter')carregar()});$('lista-usuarios')?.addEventListener('click',acaoTabela);$('lista-assinaturas')?.addEventListener('click',acaoTabela);$('credito-cancelar')?.addEventListener('click',fecharCredito);$('credito-confirmar')?.addEventListener('click',ajustarCredito);$('assinatura-cancelar')?.addEventListener('click',fecharAssinatura);$('assinatura-confirmar')?.addEventListener('click',gerenciarAssinatura);$('assinatura-acao')?.addEventListener('change',ajustarCampos);[$('modal-creditos'),$('modal-assinatura')].forEach(m=>m?.addEventListener('click',e=>{if(e.target!==m)return;m.id==='modal-creditos'?fecharCredito():fecharAssinatura()}));document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;if($('modal-creditos')?.classList.contains('ativo'))fecharCredito();else if($('modal-assinatura')?.classList.contains('ativo'))fecharAssinatura()})}
function iniciar(){eventos();carregar()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',iniciar,{once:true});else iniciar();
})();