(function(){
  'use strict';
  const $=id=>document.getElementById(id), moeda=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}), data=v=>{const d=new Date(v||'');return Number.isNaN(d.getTime())?'—':d.toLocaleString('pt-BR')}, esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
  let alvoCredito=null;
  const badge=v=>`<span class="badge ${esc(String(v||'').toLowerCase())}">${esc(v||'—')}</span>`;

  function tabela(vazia,cabecalho,linhas){return linhas.length?`<table class="table"><thead><tr>${cabecalho.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${linhas.join('')}</tbody></table>`:`<div class="empty">${esc(vazia)}</div>`}
  function renderResumo(r={}){$('admin-metricas').innerHTML=[['Usuários',r.usuarios_total||0],['Assinaturas ativas',r.assinaturas_ativas||0],['Receita total',moeda(r.receita_total)],['Pix pendentes',r.pagamentos_pendentes||0],['Essencial',r.essencial_ativos||0],['PRO',r.pro_ativos||0],['Créditos em circulação',r.creditos_em_circulacao||0]].map(([l,v])=>`<article class="card metric"><span>${l}</span><strong>${v}</strong></article>`).join('')}
  function renderUsuarios(lista=[]){$('lista-usuarios').innerHTML=tabela('Nenhum usuário encontrado.',['Usuário','Empresa','Plano','Status','Saldo Efex','Cadastro','Último acesso','Ações'],lista.map(u=>`<tr><td><strong>${esc(u.nome||u.email||'—')}</strong><br><small>${esc(u.email||'')}</small></td><td>${esc(u.nome_empresa||'—')}</td><td>${esc(u.nivel||u.plano||'grátis')}</td><td>${badge(u.status)}</td><td><strong>${Number(u.saldo_efex||0)}</strong></td><td>${data(u.criado_em)}</td><td>${data(u.last_sign_in_at)}</td><td><button class="btn gold" onclick="fsAbrirAjusteCredito('${esc(u.id)}','${esc(u.nome||u.email||'Usuário')}',${Number(u.saldo_efex||0)})">Ajustar créditos</button></td></tr>`))}
  function renderAssinaturas(lista=[]){$('lista-assinaturas').innerHTML=tabela('Nenhuma assinatura encontrada.',['Usuário','Empresa','Nível','Status','Créditos/mês','Expiração'],lista.map(a=>`<tr><td><strong>${esc(a.nome||a.email||'—')}</strong><br><small>${esc(a.email||'')}</small></td><td>${esc(a.nome_empresa||'—')}</td><td>${esc(a.nivel||a.plano||'—')}</td><td>${badge(a.status)}</td><td>${Number(a.creditos_mensais||0)}</td><td>${data(a.expira_em)}</td></tr>`))}
  function produto(p){if(p.produto_codigo==='assinatura_essencial')return'Premium Essencial';if(p.produto_codigo==='assinatura_pro')return'Premium PRO';if(String(p.produto_codigo||'').startsWith('creditos_'))return`${p.creditos||''} créditos Efex`;return p.produto_codigo||p.produto_tipo||'Pagamento'}
  function renderPagamentos(lista=[]){$('lista-pagamentos').innerHTML=tabela('Nenhum pagamento encontrado.',['Data','Usuário','Produto','Valor','Status','Pago em','Aplicado'],lista.map(p=>`<tr><td>${data(p.criado_em)}</td><td><strong>${esc(p.nome||p.email||'—')}</strong><br><small>${esc(p.email||'')}</small></td><td>${esc(produto(p))}</td><td><strong>${moeda(p.valor)}</strong></td><td>${badge(p.status)}</td><td>${data(p.pago_em)}</td><td>${p.aplicado_em?'Sim':'Não'}</td></tr>`))}
  function renderAuditoria(lista=[]){$('lista-auditoria').innerHTML=tabela('Nenhuma ação administrativa registrada.',['Data','Administrador','Ação','Entidade','Motivo'],lista.map(a=>`<tr><td>${data(a.criado_em)}</td><td>${esc(a.admin_email||a.admin_usuario_id||'—')}</td><td>${esc(a.acao)}</td><td>${esc(a.entidade_tipo)}<br><small>${esc(a.entidade_id||'')}</small></td><td>${esc(a.motivo||'—')}</td></tr>`))}

  async function carregar(){
    const {data:{session}}=await _supabase.auth.getSession();
    if(!session?.user?.id){location.href='/index.html?login=1&dest='+encodeURIComponent('/admin.html');return}
    const busca=$('admin-busca').value.trim();
    const {data,error}=await _supabase.rpc('fs_admin_painel_essencial',{p_busca:busca||null,p_limite:50,p_offset:0});
    if(error){console.error(error);document.querySelector('.admin').innerHTML='<section class="card hero"><h1>Acesso não autorizado</h1><p>Esta área é exclusiva da equipe administrativa do FS Orçamentos.</p></section>';return}
    renderResumo(data?.resumo);renderUsuarios(data?.usuarios||[]);renderAssinaturas(data?.assinaturas||[]);renderPagamentos(data?.pagamentos||[]);renderAuditoria(data?.auditoria||[]);
  }
  function abrirCredito(id,nome,saldo){alvoCredito=id;$('credito-usuario').textContent=`${nome} • saldo atual: ${saldo}`;$('credito-delta').value='';$('credito-motivo').value='';$('modal-creditos').classList.add('ativo')}
  function fecharCredito(){$('modal-creditos').classList.remove('ativo');alvoCredito=null}
  async function ajustarCredito(){const delta=Number($('credito-delta').value),motivo=$('credito-motivo').value.trim();if(!alvoCredito||!Number.isInteger(delta)||delta===0)return alert('Informe uma quantidade inteira diferente de zero.');if(motivo.length<5)return alert('Informe um motivo com pelo menos 5 caracteres.');$('credito-confirmar').disabled=true;try{const{data,error}=await _supabase.rpc('fs_admin_ajustar_creditos',{p_usuario_id:alvoCredito,p_delta:delta,p_motivo:motivo});if(error||!data?.sucesso)throw new Error(error?.message||'Não foi possível ajustar créditos.');alert(`Saldo atualizado para ${data.saldo_atual} créditos.`);fecharCredito();await carregar()}catch(e){alert(e.message)}finally{$('credito-confirmar').disabled=false}}
  document.querySelectorAll('[data-tab]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('ativo'));document.querySelectorAll('.painel').forEach(x=>x.classList.remove('ativo'));btn.classList.add('ativo');$('painel-'+btn.dataset.tab).classList.add('ativo')}));
  $('admin-buscar').addEventListener('click',carregar);$('admin-busca').addEventListener('keydown',e=>{if(e.key==='Enter')carregar()});$('credito-cancelar').addEventListener('click',fecharCredito);$('credito-confirmar').addEventListener('click',ajustarCredito);$('modal-creditos').addEventListener('click',e=>{if(e.target===$('modal-creditos'))fecharCredito()});
  window.fsAbrirAjusteCredito=abrirCredito;
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',carregar);else carregar();
})();