let ORCAMENTO_PUBLICO = null;
const FS_FUNCTIONS_URL = window.FS_SUPABASE_FUNCTIONS_URL || 'https://kvjvhoziqcevkzyszdke.supabase.co/functions/v1';
function $(id){return document.getElementById(id)}
function moeda(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function html(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function parametro(nome){return new URLSearchParams(location.search).get(nome)||''}
function msg(t,classe=''){const c=$('conteudo');if(c)c.innerHTML=`<div class="msg ${classe}">${html(t)}</div>`}
function separarItens(itens=[]){const arr=Array.isArray(itens)?itens:[];return{mao:arr.filter(i=>(i.tipo||'')==='mao_obra'),prod:arr.filter(i=>(i.tipo||'')!=='mao_obra')}}
function tabela(titulo,itens){return`<h2>${html(titulo)}</h2><table class="tabela"><thead><tr><th>Descrição</th><th>Qtd</th><th>Unit.</th><th>Subtotal</th></tr></thead><tbody>${itens.length?itens.map(i=>`<tr><td>${html(i.descricao||i.nome||'-')}</td><td>${html(i.qtd??i.quantidade??1)}</td><td>${moeda(i.valor??i.valor_unitario??0)}</td><td>${moeda(i.subtotal??i.total??0)}</td></tr>`).join(''):`<tr><td colspan="4">Nenhum item informado.</td></tr>`}</tbody></table>`}
function render(o){ORCAMENTO_PUBLICO=o;const titulo=o.titulo||'Orçamento';$('titulo').textContent=titulo;const itens=separarItens(o.itens);const extra=[o.numero_orcamento?`<div class="box"><small>Número</small><strong>${html(o.numero_orcamento)}</strong></div>`:'',o.forma_pagamento?`<div class="box"><small>Pagamento</small><strong>${html(o.forma_pagamento)}</strong></div>`:'',o.prazo_execucao?`<div class="box"><small>Prazo</small><strong>${html(o.prazo_execucao)}</strong></div>`:'',o.garantia?`<div class="box"><small>Garantia</small><strong>${html(o.garantia)}</strong></div>`:''].join('');$('conteudo').innerHTML=`<div class="info"><div class="box"><small>Cliente</small><strong>${html(o.cliente_nome||'Cliente')}</strong>${o.cliente_whatsapp?`<span>${html(o.cliente_whatsapp)}</span>`:''}</div><div class="box"><small>Status</small><strong>${html(o.status||'pendente')}</strong></div>${extra}</div>${tabela('Mão de obra',itens.mao)}${tabela('Itens / produtos',itens.prod)}<div class="total">Total: ${moeda(o.total)}</div>${o.observacoes?`<div class="obs"><strong>Observações</strong><br>${html(o.observacoes)}</div>`:''}<div class="acoes"><button type="button" class="btn ok" onclick="responderOrcamento('aprovado')">Aprovar orçamento</button><button type="button" class="btn red" onclick="responderOrcamento('recusado')">Recusar orçamento</button></div><div id="resposta-msg"></div>`}
async function carregar(){try{const token=parametro('t')||parametro('token');const id=parametro('id');if(token){const r=await fetch(`${FS_FUNCTIONS_URL}/orcamento-publico?t=${encodeURIComponent(token)}`,{method:'GET'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.erro||'Erro ao carregar orçamento.');return render(d.orcamento||d)}if(!window._supabase&&window.supabase&&window.SUPABASE_URL&&window.SUPABASE_ANON_KEY)window._supabase=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);if(!id)return msg('Link inválido. Token do orçamento não informado.','erro');const{data,error}=await _supabase.from('orcamentos').select('*').eq('id',id).maybeSingle();if(error)throw error;if(!data)return msg('Orçamento não encontrado.','erro');render(data)}catch(e){console.error(e);msg('Não foi possível carregar o orçamento. Solicite um novo link ao responsável.','erro')}}
async function responderOrcamento(status){try{if(!ORCAMENTO_PUBLICO)return;const token=parametro('t')||parametro('token')||ORCAMENTO_PUBLICO.public_token||'';const ok=confirm(status==='aprovado'?'Confirmar aprovação deste orçamento?':'Confirmar recusa deste orçamento?');if(!ok)return;let sucesso=false;if(token){const r=await fetch(`${FS_FUNCTIONS_URL}/orcamento-publico`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,status})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.erro||'Erro ao registrar resposta.');sucesso=true}else if(window._supabase&&ORCAMENTO_PUBLICO.id){const payload={status,respondido_em:new Date().toISOString()};let{error}=await _supabase.from('orcamentos').update(payload).eq('id',ORCAMENTO_PUBLICO.id);if(error){const fallback=await _supabase.from('orcamentos').update({status}).eq('id',ORCAMENTO_PUBLICO.id);error=fallback.error}if(error)throw error;sucesso=true}if(sucesso){const box=$('resposta-msg');if(box)box.innerHTML=`<div class="msg sucesso">Orçamento ${status==='aprovado'?'aprovado':'recusado'} com sucesso.</div>`;document.querySelectorAll('.acoes button').forEach(b=>b.disabled=true)}}catch(e){console.error(e);const box=$('resposta-msg');if(box)box.innerHTML='<div class="msg erro">Não foi possível registrar sua resposta. Avise o responsável pelo orçamento.</div>'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',carregar);else carregar();
window.responderOrcamento=responderOrcamento;
