let headerJaCarregado = false;
let fsMenuInicializado = false;

const FS_ROTAS_PROTEGIDAS_MENU = [
  '/gerador.html', '/gerador',
  '/painel.html', '/painel',
  '/orcamentos.html', '/orcamentos',
  '/dashboard.html', '/dashboard',
  '/fluxo-caixa.html', '/fluxo-caixa',
  '/forum.html', '/forum',
  '/social.html', '/social'
];

const FS_ROTAS_PREMIUM_MENU = [
  '/orcamentos.html', '/orcamentos',
  '/dashboard.html', '/dashboard',
  '/fluxo-caixa.html', '/fluxo-caixa'
];

const FS_ROTAS_REMOVIDAS_MENU = [
  '/gestao.html', '/gestao',
  '/clientes.html', '/clientes',
  '/cliente.html', '/cliente',
  '/veiculos.html', '/veiculos',
  '/ordens.html', '/ordens',
  '/ordem.html', '/ordem',
  '/estoque.html', '/estoque',
  '/agenda.html', '/agenda',
  '/recorrentes.html', '/recorrentes'
];

function fsModoEmbedGestao(){try{const p=new URLSearchParams(location.search);return p.get('embed')==='1'||p.get('iframe')==='1'}catch(_){return false}}
function aplicarModoEmbedGestao(){if(!fsModoEmbedGestao())return false;document.documentElement.classList.add('modo-embed-gestao');document.body?.classList.add('modo-embed-gestao');const h=document.getElementById('header-container');if(h){h.innerHTML='';h.style.display='none'}document.querySelectorAll('footer,.footer,.site-footer,.forum-footer').forEach(e=>e.style.display='none');return true}
function fsGarantirCss(id,href){if(document.getElementById(id))return;const l=document.createElement('link');l.id=id;l.rel='stylesheet';l.href=href;document.head.appendChild(l)}
function garantirCssHeaderFS(){fsGarantirCss('fs-header-clean-css','/header-clean.css?v=20260701-1');fsGarantirCss('fs-auth-clean-css','/auth-clean.css?v=20260701-1');fsGarantirCss('fs-brand-contrast-css','/brand-contrast-fix.css?v=20260701-1')}
function removerCssObsoletoTemaMarrom(){document.querySelectorAll('style').forEach(s=>{const t=s.textContent||'';if(t.includes('FS FORMAL THEME OVERRIDES')||t.includes('FS CONTRAST FIX')||t.includes('marrom no header')||t.includes('Cores oficiais: marrom'))s.remove()})}
function fsNormalizarTextoMenu(v){const p=String(v||'gratis').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();return p==='basico'||p==='gestao'?'premium':p}
function fsPaginaAtual(){const p=location.pathname||'/';return p==='/'?'/index.html':p}
function fsEstaNaPaginaGerador(){const p=fsPaginaAtual();return p.endsWith('/gerador.html')||p.endsWith('/gerador')}
function fsEstaNaHome(){const p=fsPaginaAtual();return p==='/index.html'||p.endsWith('/index.html')}
function fsDestinoProtegidoMenu(href){try{if(!href||href.startsWith('#')||href.startsWith('javascript:')||href.startsWith('mailto:')||href.startsWith('tel:'))return'';const u=new URL(href,location.origin);if(u.origin!==location.origin)return'';return `${u.pathname||'/index.html'}${u.search||''}${u.hash||''}`}catch(_){return''}}
function fsNormalizarPathMenu(destino){let p=String(destino||'').split('?')[0].split('#')[0].replace(/\/$/,'').toLowerCase();return p||'/index.html'}
function fsListaContemRotaMenu(lista,destino){const p=fsNormalizarPathMenu(destino);return lista.some(r=>p===r||p===r.replace(/\.html$/,''))}
function fsEhRotaRemovidaMenu(destino){return fsListaContemRotaMenu(FS_ROTAS_REMOVIDAS_MENU,destino)}
function fsEhRotaProtegidaMenu(destino){return fsListaContemRotaMenu(FS_ROTAS_PROTEGIDAS_MENU,destino)}
function fsPlanoMinimoDaRotaMenu(destino){if(fsEhRotaRemovidaMenu(destino))return'removida';if(!fsEhRotaProtegidaMenu(destino))return'publico';if(fsListaContemRotaMenu(FS_ROTAS_PREMIUM_MENU,destino))return'premium';return'gratis'}
function fsPlanoMenuAtual(){return fsNormalizarTextoMenu(localStorage.getItem('usuario_plano')||'gratis')}
function fsPlanoMenuOrdem(plano){return fsNormalizarTextoMenu(plano)==='premium'?1:0}
function fsPlanoPermiteDestinoMenu(destino,plano=fsPlanoMenuAtual()){const min=fsPlanoMinimoDaRotaMenu(destino);if(min==='removida')return false;if(min==='publico'||min==='gratis')return true;return fsPlanoMenuOrdem(plano)>=fsPlanoMenuOrdem(min)}
function fsRedirecionarIndexSePlanoNaoPermite(session,destino=fsPaginaAtual()){if(fsEhRotaRemovidaMenu(destino)){location.replace('/gerador.html');return true}if(!session?.user?.id)return false;if(!fsEhRotaProtegidaMenu(destino))return false;if(fsPlanoPermiteDestinoMenu(destino))return false;try{localStorage.removeItem('fs_destino_apos_login')}catch(_){}location.replace('/planos.html#assinar-plano-premium');return true}
function fsSalvarDestinoProtegidoMenu(destino){try{const d=fsDestinoProtegidoMenu(destino)||'/gerador.html';localStorage.setItem('fs_destino_apos_login',d);return d}catch(_){return'/gerador.html'}}
function fsAbrirLoginParaDestinoProtegido(destino){const d=fsSalvarDestinoProtegidoMenu(destino);fecharMenuMobileSeAberto();if(fsEstaNaHome()&&typeof abrirModalLogin==='function'){abrirModalLogin();return}location.href=`/index.html?login=1&dest=${encodeURIComponent(d)}`}
async function obterSessaoAtualMenu(){try{if(!window._supabase)return null;const{data,error}=await _supabase.auth.getSession();return error?null:data?.session||null}catch(_){return null}}
async function carregarHeaderHtmlMenu(){for(const c of ['/header.html','header.html','./header.html']){try{const r=await fetch(c,{cache:'no-cache'});if(r.ok)return await r.text()}catch(_){}}throw new Error('Não foi possível carregar header.html.')}
function fecharMenuMobileSeAberto(){document.querySelector('.header-menu-linha')?.classList.remove('menu-aberto');document.querySelector('.main-header')?.classList.remove('menu-aberto')}
function toggleMenuMobile(){const m=document.querySelector('.header-menu-linha'),h=document.querySelector('.main-header');m?.classList.toggle('menu-aberto');h?.classList.toggle('menu-aberto',m?.classList.contains('menu-aberto'))}
function configurarLinksDoHeader(){document.querySelectorAll('.header-menu-linha a').forEach(link=>{if(link.dataset.fsHeaderLinkConfigurado==='sim')return;link.dataset.fsHeaderLinkConfigurado='sim';link.addEventListener('click',async e=>{const d=fsDestinoProtegidoMenu(link.getAttribute('href')||'');if(fsEhRotaRemovidaMenu(d)){e.preventDefault();location.href='/gerador.html';return}if(!fsEhRotaProtegidaMenu(d)){fecharMenuMobileSeAberto();return}const s=await obterSessaoAtualMenu();if(!s?.user?.id){e.preventDefault();fsAbrirLoginParaDestinoProtegido(d);return}if(!fsPlanoPermiteDestinoMenu(d)){e.preventDefault();fecharMenuMobileSeAberto();location.href='/planos.html#assinar-plano-premium';return}fecharMenuMobileSeAberto()})})}
function configurarDropdownsHeader(){return}
function marcarLinkAtivoHeader(){const p=fsPaginaAtual();document.querySelectorAll('.header-menu-linha a').forEach(a=>{const h=(a.getAttribute('href')||'')==='/'?'/index.html':a.getAttribute('href')||'';a.classList.toggle('ativo',!!h&&(p===h||p.endsWith(h)))})}
function aplicarVisibilidadeMenuPorPlano(){const n=fsPlanoMenuOrdem(fsPlanoMenuAtual());document.querySelectorAll('[data-plano-min]').forEach(link=>{const min=fsPlanoMenuOrdem(link.getAttribute('data-plano-min')||'gratis');const ok=n>=min;const li=link.closest('li');if(li)li.style.display=ok?'':'none';else link.style.display=ok?'':'none'})}
async function verificarExpiracaoTestePremiumMenu(){try{if(!window._supabase)return null;const{data:{session}}=await _supabase.auth.getSession();if(!session?.user?.id)return null;const{data,error}=await _supabase.rpc('verificar_expiracao_teste_premium');if(error)return null;if(data?.plano)localStorage.setItem('usuario_plano',fsNormalizarTextoMenu(data.plano));if(data?.plano_status)localStorage.setItem('usuario_plano_status',data.plano_status);else localStorage.removeItem('usuario_plano_status');if(data?.plano_expira_em)localStorage.setItem('usuario_plano_expira_em',data.plano_expira_em);else localStorage.removeItem('usuario_plano_expira_em');return data||null}catch(_){return null}}
async function atualizarHeaderUsuario(session){const saudacao=document.getElementById('usuario-saudacao'),entrarD=document.getElementById('btn-header-entrar'),sairD=document.getElementById('btn-header-sair'),entrarM=document.getElementById('btn-menu-mobile-entrar'),sairM=document.getElementById('btn-menu-mobile-sair'),not=document.getElementById('btn-notificacoes'),cont=document.getElementById('contador-notificacoes');if(!saudacao)return;if(!session?.user?.id){saudacao.innerText='Olá, Convidado';if(entrarD)entrarD.style.display='inline-flex';if(sairD)sairD.style.display='none';if(entrarM)entrarM.style.display='inline-flex';if(sairM)sairM.style.display='none';if(not)not.style.display='none';if(cont)cont.style.display='none';['usuario_nome','usuario_email','usuario_plano'].forEach(k=>localStorage.removeItem(k));aplicarVisibilidadeMenuPorPlano();return}let nome=localStorage.getItem('usuario_nome')||session.user.user_metadata?.nome||session.user.user_metadata?.name||session.user.email?.split('@')[0]||'Visitante';try{await verificarExpiracaoTestePremiumMenu();if(window._supabase){const{data:p,error}=await _supabase.from('perfis').select('nome,nome_empresa,plano,plano_status,plano_expira_em').eq('id',session.user.id).maybeSingle();if(!error&&p){nome=p.nome||p.nome_empresa||nome;localStorage.setItem('usuario_nome',nome);localStorage.setItem('usuario_email',session.user.email||'');localStorage.setItem('usuario_plano',fsNormalizarTextoMenu(p.plano||'gratis'));if(p.plano_status)localStorage.setItem('usuario_plano_status',p.plano_status);else localStorage.removeItem('usuario_plano_status');if(p.plano_expira_em)localStorage.setItem('usuario_plano_expira_em',p.plano_expira_em);else localStorage.removeItem('usuario_plano_expira_em')}}}catch(_){}saudacao.innerText=`Olá, ${nome}`;if(entrarD)entrarD.style.display='none';if(sairD)sairD.style.display='inline-flex';if(entrarM)entrarM.style.display='none';if(sairM)sairM.style.display='inline-flex';if(not)not.style.display=fsPlanoMenuAtual()==='premium'?'inline-flex':'none';if(cont&&fsPlanoMenuAtual()!=='premium')cont.style.display='none';aplicarVisibilidadeMenuPorPlano()}
function irParaLogin(){fecharMenuMobileSeAberto();if(typeof abrirModalLogin==='function')return abrirModalLogin();location.href='/index.html?login=1'}
async function deslogar(){try{fecharMenuMobileSeAberto();if(window._supabase)await _supabase.auth.signOut();['id','usuario_nome','usuario_email','usuario_plano','usuario_plano_status','usuario_plano_expira_em','nome_empresa','telefone_empresa','endereco_empresa','cnpj_empresa','foto_url'].forEach(k=>localStorage.removeItem(k));removerBotaoFlutuanteGeradorGlobal();await atualizarHeaderUsuario(null);location.href='/index.html'}catch(e){console.error(e);alert('Não foi possível sair da conta. Tente novamente.')}}
async function controlarBotaoFlutuanteGeradorGlobal(sessionRecebida=undefined){if(fsModoEmbedGestao())return removerBotaoFlutuanteGeradorGlobal();let s=sessionRecebida;if(s===undefined)s=await obterSessaoAtualMenu();if(!s?.user?.id||fsEstaNaPaginaGerador())return removerBotaoFlutuanteGeradorGlobal();criarBotaoFlutuanteGeradorGlobal()}
function criarBotaoFlutuanteGeradorGlobal(){if(document.getElementById('btn-flutuante-gerador-global'))return;const b=document.createElement('button');b.type='button';b.id='btn-flutuante-gerador-global';b.innerHTML='🧾 <span>Gerar orçamento</span>';b.title='Gerar orçamento';b.setAttribute('aria-label','Gerar orçamento');b.onclick=abrirGeradorGlobal;document.body.appendChild(b)}
function removerBotaoFlutuanteGeradorGlobal(){document.getElementById('btn-flutuante-gerador-global')?.remove();document.body.classList.remove('gerador-aberto')}
async function abrirGeradorGlobal(){const s=await obterSessaoAtualMenu();if(!s?.user?.id){removerBotaoFlutuanteGeradorGlobal();if(fsEstaNaHome()&&typeof abrirModalLogin==='function')return abrirModalLogin();location.href='/index.html?login=1&dest='+encodeURIComponent('/gerador.html');return}location.href='/gerador.html'}
function removerParametrosUrlMenu(){history.replaceState({},document.title,location.origin+location.pathname)}
function abrirLoginAutomaticamenteSeSolicitado(){const p=new URLSearchParams(location.search),d=p.get('dest')||'';if(d&&fsEhRotaProtegidaMenu(d))fsSalvarDestinoProtegidoMenu(d);if(p.get('login')!=='1')return;setTimeout(()=>{if(typeof abrirModalLogin==='function')abrirModalLogin();removerParametrosUrlMenu()},500)}
async function abrirGeradorAutomaticamenteSeSolicitado(){const p=new URLSearchParams(location.search);if(p.get('abrirGerador')!=='1')return;const s=await obterSessaoAtualMenu();removerParametrosUrlMenu();if(!s?.user?.id){fsSalvarDestinoProtegidoMenu('/gerador.html');if(typeof abrirModalLogin==='function')abrirModalLogin();else location.href='/index.html?login=1&dest='+encodeURIComponent('/gerador.html');return}location.href='/gerador.html'}
function configurarHeaderInteligente(){const h=document.getElementById('header-container');if(!h)return;h.classList.remove('header-oculto');h.classList.add('header-visivel')}
function controlarHeaderInteligente(){configurarHeaderInteligente()}
async function carregarMenu(sessionRecebida=undefined){removerCssObsoletoTemaMarrom();if(aplicarModoEmbedGestao())return;garantirCssHeaderFS();const h=document.getElementById('header-container');if(!h)return;try{if(!headerJaCarregado){h.innerHTML=await carregarHeaderHtmlMenu();h.style.display='block';headerJaCarregado=true;configurarLinksDoHeader();configurarDropdownsHeader();marcarLinkAtivoHeader();configurarHeaderInteligente()}const s=sessionRecebida===undefined?await obterSessaoAtualMenu():sessionRecebida;await atualizarHeaderUsuario(s||null);aplicarVisibilidadeMenuPorPlano();if(fsRedirecionarIndexSePlanoNaoPermite(s||null,fsPaginaAtual()))return;await controlarBotaoFlutuanteGeradorGlobal(s||null);configurarHeaderInteligente()}catch(e){console.error('Erro ao carregar menu:',e)}}
async function inicializarMenuFS(){removerCssObsoletoTemaMarrom();if(fsMenuInicializado)return;fsMenuInicializado=true;if(aplicarModoEmbedGestao())return;garantirCssHeaderFS();await carregarMenu();const s=await obterSessaoAtualMenu(),d=fsPaginaAtual();if(!s?.user?.id&&fsEhRotaProtegidaMenu(d)&&!fsEstaNaHome()){fsAbrirLoginParaDestinoProtegido(d);return}if(fsRedirecionarIndexSePlanoNaoPermite(s||null,d))return;abrirLoginAutomaticamenteSeSolicitado();await abrirGeradorAutomaticamenteSeSolicitado();if(window._supabase){_supabase.auth.onAuthStateChange(async(_,session)=>{removerCssObsoletoTemaMarrom();await atualizarHeaderUsuario(session||null);aplicarVisibilidadeMenuPorPlano();if(fsRedirecionarIndexSePlanoNaoPermite(session||null,fsPaginaAtual()))return;await controlarBotaoFlutuanteGeradorGlobal(session||null);if(!session)removerBotaoFlutuanteGeradorGlobal();configurarHeaderInteligente()})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inicializarMenuFS);else inicializarMenuFS();
window.carregarMenu=carregarMenu;window.verificarExpiracaoTestePremiumMenu=verificarExpiracaoTestePremiumMenu;window.atualizarHeaderUsuario=atualizarHeaderUsuario;window.irParaLogin=irParaLogin;window.toggleMenuMobile=toggleMenuMobile;window.deslogar=deslogar;window.abrirGeradorGlobal=abrirGeradorGlobal;window.controlarBotaoFlutuanteGeradorGlobal=controlarBotaoFlutuanteGeradorGlobal;window.configurarHeaderInteligente=configurarHeaderInteligente;window.controlarHeaderInteligente=controlarHeaderInteligente;window.aplicarVisibilidadeMenuPorPlano=aplicarVisibilidadeMenuPorPlano;window.inicializarMenuFS=inicializarMenuFS;window.fsAbrirLoginParaDestinoProtegido=fsAbrirLoginParaDestinoProtegido;window.fsSalvarDestinoProtegidoMenu=fsSalvarDestinoProtegidoMenu;window.removerCssObsoletoTemaMarrom=removerCssObsoletoTemaMarrom;window.fsRedirecionarIndexSePlanoNaoPermite=fsRedirecionarIndexSePlanoNaoPermite;window.fsPlanoPermiteDestinoMenu=fsPlanoPermiteDestinoMenu;
