-- FS Orçamentos - Catálogo de marcas e modelos de veículos que rodam no Brasil
-- Execute no Supabase SQL Editor.
-- Este script NÃO insere registros na sua tabela public.veiculos,
-- porque essa tabela exige user_id e placa. Ele cria um catálogo global
-- para alimentar selects/modais de marca e modelo no sistema.

begin;

create table if not exists public.veiculo_marcas_catalogo (
  id bigserial primary key,
  nome text not null,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  constraint veiculo_marcas_catalogo_nome_unique unique (nome)
);

create table if not exists public.veiculo_modelos_catalogo (
  id bigserial primary key,
  marca_id bigint not null references public.veiculo_marcas_catalogo(id) on delete cascade,
  nome text not null,
  tipo text not null default 'carro',
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  constraint veiculo_modelos_catalogo_tipo_check check (
    tipo in ('carro', 'picape', 'van_utilitario', 'caminhao_utilitario', 'moto')
  ),
  constraint veiculo_modelos_catalogo_marca_nome_unique unique (marca_id, nome)
);

create index if not exists idx_veiculo_marcas_catalogo_nome
  on public.veiculo_marcas_catalogo (nome);

create index if not exists idx_veiculo_modelos_catalogo_marca_id
  on public.veiculo_modelos_catalogo (marca_id);

create index if not exists idx_veiculo_modelos_catalogo_nome
  on public.veiculo_modelos_catalogo (nome);

create index if not exists idx_veiculo_modelos_catalogo_tipo
  on public.veiculo_modelos_catalogo (tipo);

insert into public.veiculo_marcas_catalogo (nome)
values
  ('Audi'),
  ('BMW'),
  ('BMW Motorrad'),
  ('BYD'),
  ('Chery'),
  ('Chevrolet'),
  ('Citroën'),
  ('Fiat'),
  ('Ford'),
  ('GWM'),
  ('Haojue'),
  ('Harley-Davidson'),
  ('Honda'),
  ('Hyundai'),
  ('Iveco'),
  ('Jac'),
  ('Jeep'),
  ('Kasinski'),
  ('Kia'),
  ('Land Rover'),
  ('Mercedes-Benz'),
  ('Mitsubishi'),
  ('Nissan'),
  ('Peugeot'),
  ('Porsche'),
  ('Ram'),
  ('Renault'),
  ('Renault Trucks'),
  ('Royal Enfield'),
  ('Shineray'),
  ('Subaru'),
  ('Suzuki'),
  ('Toyota'),
  ('Triumph'),
  ('Volkswagen'),
  ('Volvo'),
  ('Yamaha'),
  ('Yamaha Motos')
on conflict (nome) do nothing;

insert into public.veiculo_modelos_catalogo (marca_id, nome, tipo)
select m.id, v.modelo, v.tipo
from (
  values
    ('Fiat', 'Strada', 'picape'),
    ('Fiat', 'Toro', 'picape'),
    ('Fiat', 'Argo', 'carro'),
    ('Fiat', 'Mobi', 'carro'),
    ('Fiat', 'Cronos', 'carro'),
    ('Fiat', 'Pulse', 'carro'),
    ('Fiat', 'Fastback', 'carro'),
    ('Fiat', 'Fiorino', 'van_utilitario'),
    ('Fiat', 'Uno', 'carro'),
    ('Fiat', 'Palio', 'carro'),
    ('Fiat', 'Siena', 'carro'),
    ('Fiat', 'Grand Siena', 'carro'),
    ('Fiat', 'Idea', 'carro'),
    ('Fiat', 'Punto', 'carro'),
    ('Fiat', 'Bravo', 'carro'),
    ('Fiat', 'Stilo', 'carro'),
    ('Fiat', 'Doblò', 'van_utilitario'),
    ('Fiat', 'Ducato', 'van_utilitario'),
    ('Fiat', 'Linea', 'carro'),
    ('Fiat', 'Freemont', 'carro'),
    ('Fiat', 'Weekend', 'carro'),
    ('Fiat', 'Tempra', 'carro'),
    ('Fiat', '147', 'carro'),
    ('Chevrolet', 'Onix', 'carro'),
    ('Chevrolet', 'Onix Plus', 'carro'),
    ('Chevrolet', 'Prisma', 'carro'),
    ('Chevrolet', 'Celta', 'carro'),
    ('Chevrolet', 'Corsa', 'carro'),
    ('Chevrolet', 'Classic', 'carro'),
    ('Chevrolet', 'Cobalt', 'carro'),
    ('Chevrolet', 'Cruze', 'carro'),
    ('Chevrolet', 'Cruze Sport6', 'carro'),
    ('Chevrolet', 'Tracker', 'carro'),
    ('Chevrolet', 'Spin', 'carro'),
    ('Chevrolet', 'Montana', 'picape'),
    ('Chevrolet', 'S10', 'picape'),
    ('Chevrolet', 'Trailblazer', 'carro'),
    ('Chevrolet', 'Astra', 'carro'),
    ('Chevrolet', 'Vectra', 'carro'),
    ('Chevrolet', 'Meriva', 'carro'),
    ('Chevrolet', 'Zafira', 'carro'),
    ('Chevrolet', 'Agile', 'carro'),
    ('Chevrolet', 'Sonic', 'carro'),
    ('Chevrolet', 'Captiva', 'carro'),
    ('Chevrolet', 'Omega', 'carro'),
    ('Chevrolet', 'Opala', 'carro'),
    ('Chevrolet', 'Chevette', 'carro'),
    ('Chevrolet', 'Kadett', 'carro'),
    ('Chevrolet', 'Monza', 'carro'),
    ('Chevrolet', 'Caravan', 'carro'),
    ('Volkswagen', 'Gol', 'carro'),
    ('Volkswagen', 'Voyage', 'carro'),
    ('Volkswagen', 'Saveiro', 'picape'),
    ('Volkswagen', 'Fox', 'carro'),
    ('Volkswagen', 'CrossFox', 'carro'),
    ('Volkswagen', 'SpaceFox', 'carro'),
    ('Volkswagen', 'Polo', 'carro'),
    ('Volkswagen', 'Virtus', 'carro'),
    ('Volkswagen', 'Nivus', 'carro'),
    ('Volkswagen', 'T-Cross', 'carro'),
    ('Volkswagen', 'Taos', 'carro'),
    ('Volkswagen', 'Jetta', 'carro'),
    ('Volkswagen', 'Golf', 'carro'),
    ('Volkswagen', 'Up', 'carro'),
    ('Volkswagen', 'Fusca', 'carro'),
    ('Volkswagen', 'Kombi', 'carro'),
    ('Volkswagen', 'Parati', 'carro'),
    ('Volkswagen', 'Santana', 'carro'),
    ('Volkswagen', 'Logus', 'carro'),
    ('Volkswagen', 'Pointer', 'carro'),
    ('Volkswagen', 'Passat', 'carro'),
    ('Volkswagen', 'Amarok', 'picape'),
    ('Volkswagen', 'Tiguan', 'carro'),
    ('Volkswagen', 'Touareg', 'carro'),
    ('Volkswagen', 'Brasilia', 'carro'),
    ('Volkswagen', 'Variant', 'carro'),
    ('Toyota', 'Corolla', 'carro'),
    ('Toyota', 'Corolla Cross', 'carro'),
    ('Toyota', 'Etios', 'carro'),
    ('Toyota', 'Yaris Hatch', 'carro'),
    ('Toyota', 'Yaris Sedan', 'carro'),
    ('Toyota', 'Hilux', 'picape'),
    ('Toyota', 'Hilux SW4', 'carro'),
    ('Toyota', 'RAV4', 'carro'),
    ('Toyota', 'Camry', 'carro'),
    ('Toyota', 'Bandeirante', 'carro'),
    ('Toyota', 'Prius', 'carro'),
    ('Toyota', 'C-HR', 'carro'),
    ('Honda', 'Civic', 'carro'),
    ('Honda', 'City', 'carro'),
    ('Honda', 'City Hatchback', 'carro'),
    ('Honda', 'Fit', 'carro'),
    ('Honda', 'HR-V', 'carro'),
    ('Honda', 'WR-V', 'carro'),
    ('Honda', 'CR-V', 'carro'),
    ('Honda', 'Accord', 'carro'),
    ('Honda', 'Civic Si', 'carro'),
    ('Honda', 'ZR-V', 'carro'),
    ('Hyundai', 'HB20', 'carro'),
    ('Hyundai', 'HB20S', 'carro'),
    ('Hyundai', 'Creta', 'carro'),
    ('Hyundai', 'Tucson', 'carro'),
    ('Hyundai', 'ix35', 'carro'),
    ('Hyundai', 'Santa Fe', 'carro'),
    ('Hyundai', 'Azera', 'carro'),
    ('Hyundai', 'Elantra', 'carro'),
    ('Hyundai', 'i30', 'carro'),
    ('Hyundai', 'HR', 'van_utilitario'),
    ('Hyundai', 'Veloster', 'carro'),
    ('Hyundai', 'Veracruz', 'carro'),
    ('Ford', 'Ka', 'carro'),
    ('Ford', 'Ka Sedan', 'carro'),
    ('Ford', 'Fiesta', 'carro'),
    ('Ford', 'Fiesta Sedan', 'carro'),
    ('Ford', 'EcoSport', 'carro'),
    ('Ford', 'Focus', 'carro'),
    ('Ford', 'Focus Sedan', 'carro'),
    ('Ford', 'Fusion', 'carro'),
    ('Ford', 'Ranger', 'picape'),
    ('Ford', 'Territory', 'carro'),
    ('Ford', 'Maverick', 'picape'),
    ('Ford', 'Edge', 'carro'),
    ('Ford', 'Courier', 'picape'),
    ('Ford', 'Escort', 'carro'),
    ('Ford', 'Verona', 'carro'),
    ('Ford', 'Del Rey', 'carro'),
    ('Ford', 'Corcel', 'carro'),
    ('Ford', 'Belina', 'carro'),
    ('Ford', 'F-1000', 'picape'),
    ('Ford', 'F-250', 'picape'),
    ('Renault', 'Kwid', 'carro'),
    ('Renault', 'Sandero', 'carro'),
    ('Renault', 'Logan', 'carro'),
    ('Renault', 'Duster', 'carro'),
    ('Renault', 'Duster Oroch', 'picape'),
    ('Renault', 'Captur', 'carro'),
    ('Renault', 'Kardian', 'carro'),
    ('Renault', 'Megane', 'carro'),
    ('Renault', 'Fluence', 'carro'),
    ('Renault', 'Clio', 'carro'),
    ('Renault', 'Scenic', 'carro'),
    ('Renault', 'Symbol', 'carro'),
    ('Renault', 'Master', 'van_utilitario'),
    ('Renault', 'Kangoo', 'van_utilitario'),
    ('Jeep', 'Renegade', 'carro'),
    ('Jeep', 'Compass', 'carro'),
    ('Jeep', 'Commander', 'carro'),
    ('Jeep', 'Wrangler', 'carro'),
    ('Jeep', 'Cherokee', 'carro'),
    ('Jeep', 'Grand Cherokee', 'carro'),
    ('Jeep', 'Gladiator', 'carro'),
    ('Nissan', 'March', 'carro'),
    ('Nissan', 'Versa', 'carro'),
    ('Nissan', 'Sentra', 'carro'),
    ('Nissan', 'Kicks', 'carro'),
    ('Nissan', 'Kicks Play', 'carro'),
    ('Nissan', 'Frontier', 'picape'),
    ('Nissan', 'Livina', 'carro'),
    ('Nissan', 'Grand Livina', 'carro'),
    ('Nissan', 'Tiida', 'carro'),
    ('Nissan', 'X-Trail', 'carro'),
    ('Nissan', 'Leaf', 'carro'),
    ('Peugeot', '206', 'carro'),
    ('Peugeot', '207', 'carro'),
    ('Peugeot', '208', 'carro'),
    ('Peugeot', '2008', 'carro'),
    ('Peugeot', '307', 'carro'),
    ('Peugeot', '308', 'carro'),
    ('Peugeot', '3008', 'carro'),
    ('Peugeot', '408', 'carro'),
    ('Peugeot', 'Partner', 'van_utilitario'),
    ('Peugeot', 'Hoggar', 'picape'),
    ('Peugeot', 'Expert', 'van_utilitario'),
    ('Peugeot', 'Boxer', 'van_utilitario'),
    ('Citroën', 'C3', 'carro'),
    ('Citroën', 'C3 Aircross', 'carro'),
    ('Citroën', 'C4', 'carro'),
    ('Citroën', 'C4 Cactus', 'carro'),
    ('Citroën', 'C4 Lounge', 'carro'),
    ('Citroën', 'Xsara Picasso', 'carro'),
    ('Citroën', 'Aircross', 'carro'),
    ('Citroën', 'Berlingo', 'van_utilitario'),
    ('Citroën', 'Jumper', 'van_utilitario'),
    ('Citroën', 'Jumpy', 'van_utilitario'),
    ('Citroën', 'Basalt', 'carro'),
    ('Mitsubishi', 'L200 Triton', 'picape'),
    ('Mitsubishi', 'Pajero', 'carro'),
    ('Mitsubishi', 'Pajero TR4', 'carro'),
    ('Mitsubishi', 'Outlander', 'carro'),
    ('Mitsubishi', 'ASX', 'carro'),
    ('Mitsubishi', 'Eclipse Cross', 'carro'),
    ('Mitsubishi', 'Lancer', 'carro'),
    ('Mitsubishi', 'Airtrek', 'carro'),
    ('Kia', 'Sportage', 'carro'),
    ('Kia', 'Sorento', 'carro'),
    ('Kia', 'Cerato', 'carro'),
    ('Kia', 'Soul', 'carro'),
    ('Kia', 'Picanto', 'carro'),
    ('Kia', 'Bongo', 'van_utilitario'),
    ('Kia', 'Carnival', 'carro'),
    ('Kia', 'Optima', 'carro'),
    ('Kia', 'Stonic', 'carro'),
    ('BMW', 'Série 1', 'carro'),
    ('BMW', 'Série 3', 'carro'),
    ('BMW', 'Série 5', 'carro'),
    ('BMW', 'X1', 'carro'),
    ('BMW', 'X2', 'carro'),
    ('BMW', 'X3', 'carro'),
    ('BMW', 'X4', 'carro'),
    ('BMW', 'X5', 'carro'),
    ('BMW', 'X6', 'carro'),
    ('BMW', '320i', 'carro'),
    ('BMW', '118i', 'carro'),
    ('Mercedes-Benz', 'Classe A', 'carro'),
    ('Mercedes-Benz', 'Classe B', 'carro'),
    ('Mercedes-Benz', 'Classe C', 'carro'),
    ('Mercedes-Benz', 'Classe E', 'carro'),
    ('Mercedes-Benz', 'CLA', 'carro'),
    ('Mercedes-Benz', 'GLA', 'carro'),
    ('Mercedes-Benz', 'GLB', 'carro'),
    ('Mercedes-Benz', 'GLC', 'carro'),
    ('Mercedes-Benz', 'Sprinter', 'van_utilitario'),
    ('Mercedes-Benz', 'C 180', 'carro'),
    ('Mercedes-Benz', 'C 200', 'carro'),
    ('Audi', 'A1', 'carro'),
    ('Audi', 'A3', 'carro'),
    ('Audi', 'A4', 'carro'),
    ('Audi', 'A5', 'carro'),
    ('Audi', 'A6', 'carro'),
    ('Audi', 'Q3', 'carro'),
    ('Audi', 'Q5', 'carro'),
    ('Audi', 'Q7', 'carro'),
    ('Audi', 'Q8', 'carro'),
    ('Audi', 'TT', 'carro'),
    ('Volvo', 'XC40', 'carro'),
    ('Volvo', 'XC60', 'carro'),
    ('Volvo', 'XC90', 'carro'),
    ('Volvo', 'S60', 'carro'),
    ('Volvo', 'V40', 'carro'),
    ('Volvo', 'C40', 'carro'),
    ('Chery', 'Tiggo 2', 'carro'),
    ('Chery', 'Tiggo 3X', 'carro'),
    ('Chery', 'Tiggo 5X', 'carro'),
    ('Chery', 'Tiggo 7', 'carro'),
    ('Chery', 'Tiggo 8', 'carro'),
    ('Chery', 'Arrizo 5', 'carro'),
    ('Chery', 'QQ', 'carro'),
    ('Chery', 'Face', 'carro'),
    ('Chery', 'Celer', 'carro'),
    ('BYD', 'Dolphin', 'carro'),
    ('BYD', 'Dolphin Mini', 'carro'),
    ('BYD', 'Song Plus', 'carro'),
    ('BYD', 'Song Pro', 'carro'),
    ('BYD', 'Yuan Plus', 'carro'),
    ('BYD', 'Seal', 'carro'),
    ('BYD', 'King', 'carro'),
    ('BYD', 'Tan', 'carro'),
    ('BYD', 'Han', 'carro'),
    ('GWM', 'Haval H6', 'carro'),
    ('GWM', 'Ora 03', 'carro'),
    ('GWM', 'Tank 300', 'carro'),
    ('GWM', 'Poer', 'picape'),
    ('Ram', 'Rampage', 'picape'),
    ('Ram', '1500', 'picape'),
    ('Ram', '2500', 'picape'),
    ('Ram', '3500', 'picape'),
    ('Suzuki', 'Jimny', 'carro'),
    ('Suzuki', 'Grand Vitara', 'carro'),
    ('Suzuki', 'Vitara', 'carro'),
    ('Suzuki', 'SX4', 'carro'),
    ('Suzuki', 'Swift', 'carro'),
    ('Suzuki', 'S-Cross', 'carro'),
    ('Subaru', 'Forester', 'carro'),
    ('Subaru', 'Impreza', 'carro'),
    ('Subaru', 'XV', 'carro'),
    ('Subaru', 'Outback', 'carro'),
    ('Subaru', 'Legacy', 'carro'),
    ('Land Rover', 'Defender', 'carro'),
    ('Land Rover', 'Discovery', 'carro'),
    ('Land Rover', 'Discovery Sport', 'carro'),
    ('Land Rover', 'Range Rover Evoque', 'carro'),
    ('Land Rover', 'Range Rover Sport', 'carro'),
    ('Land Rover', 'Freelander', 'carro'),
    ('Porsche', 'Macan', 'carro'),
    ('Porsche', 'Cayenne', 'carro'),
    ('Porsche', 'Panamera', 'carro'),
    ('Porsche', '911', 'carro'),
    ('Porsche', 'Boxster', 'carro'),
    ('Porsche', 'Cayman', 'carro'),
    ('Jac', 'J2', 'carro'),
    ('Jac', 'J3', 'carro'),
    ('Jac', 'J5', 'carro'),
    ('Jac', 'J6', 'carro'),
    ('Jac', 'T40', 'carro'),
    ('Jac', 'T50', 'carro'),
    ('Jac', 'T60', 'carro'),
    ('Jac', 'E-JS1', 'carro'),
    ('Jac', 'E-JS4', 'carro'),
    ('Iveco', 'Daily', 'caminhao_utilitario'),
    ('Iveco', 'Tector', 'caminhao_utilitario'),
    ('Iveco', 'S-Way', 'caminhao_utilitario'),
    ('Iveco', 'Stralis', 'caminhao_utilitario'),
    ('Renault Trucks', 'Master', 'van_utilitario'),
    ('Honda', 'CG 160', 'moto'),
    ('Honda', 'Biz', 'moto'),
    ('Honda', 'NXR 160 Bros', 'moto'),
    ('Honda', 'Pop 110i', 'moto'),
    ('Honda', 'CB 300F', 'moto'),
    ('Honda', 'XRE 300', 'moto'),
    ('Honda', 'XRE 190', 'moto'),
    ('Honda', 'PCX', 'moto'),
    ('Honda', 'Elite 125', 'moto'),
    ('Honda', 'Fan 160', 'moto'),
    ('Honda', 'Titan 160', 'moto'),
    ('Honda', 'Twister', 'moto'),
    ('Honda', 'CB 500F', 'moto'),
    ('Honda', 'CB 500X', 'moto'),
    ('Yamaha', 'YBR 150 Factor', 'moto'),
    ('Yamaha', 'Fazer 150', 'moto'),
    ('Yamaha', 'Fazer 250', 'moto'),
    ('Yamaha', 'Lander 250', 'moto'),
    ('Yamaha', 'Crosser 150', 'moto'),
    ('Yamaha', 'NMAX', 'moto'),
    ('Yamaha', 'Neo 125', 'moto'),
    ('Yamaha', 'MT-03', 'moto'),
    ('Yamaha', 'R3', 'moto'),
    ('Yamaha', 'XMAX', 'moto'),
    ('Shineray', 'Jet 125', 'moto'),
    ('Shineray', 'Worker 125', 'moto'),
    ('Shineray', 'XY 50', 'moto'),
    ('Shineray', 'Rio 125', 'moto'),
    ('Haojue', 'DK 150', 'moto'),
    ('Haojue', 'Chopper Road 150', 'moto'),
    ('Haojue', 'DR 160', 'moto'),
    ('Haojue', 'Lindy 125', 'moto'),
    ('BMW Motorrad', 'G 310 R', 'moto'),
    ('BMW Motorrad', 'G 310 GS', 'moto'),
    ('BMW Motorrad', 'F 850 GS', 'moto'),
    ('BMW Motorrad', 'R 1250 GS', 'moto'),
    ('BMW Motorrad', 'S 1000 RR', 'moto'),
    ('Royal Enfield', 'Classic 350', 'moto'),
    ('Royal Enfield', 'Meteor 350', 'moto'),
    ('Royal Enfield', 'Hunter 350', 'moto'),
    ('Royal Enfield', 'Himalayan', 'moto'),
    ('Royal Enfield', 'Interceptor 650', 'moto'),
    ('Royal Enfield', 'Continental GT 650', 'moto'),
    ('Triumph', 'Tiger 900', 'moto'),
    ('Triumph', 'Tiger 1200', 'moto'),
    ('Triumph', 'Street Triple', 'moto'),
    ('Triumph', 'Speed Twin', 'moto'),
    ('Triumph', 'Bonneville', 'moto'),
    ('Harley-Davidson', 'Sportster', 'moto'),
    ('Harley-Davidson', 'Iron 883', 'moto'),
    ('Harley-Davidson', 'Fat Boy', 'moto'),
    ('Harley-Davidson', 'Street Glide', 'moto'),
    ('Harley-Davidson', 'Road King', 'moto'),
    ('Kasinski', 'Comet 250', 'moto'),
    ('Kasinski', 'Mirage 250', 'moto'),
    ('Kasinski', 'CRZ 150', 'moto'),
    ('Yamaha Motos', 'XJ6', 'moto'),
    ('Yamaha Motos', 'XT 660R', 'moto'),
    ('Yamaha Motos', 'XTZ 250 Ténéré', 'moto')
) as v(marca, modelo, tipo)
join public.veiculo_marcas_catalogo m on m.nome = v.marca
on conflict (marca_id, nome) do update
set tipo = excluded.tipo,
    ativo = true;

-- RLS: catálogo pode ser lido pelo frontend com chave anon/authenticated.
alter table public.veiculo_marcas_catalogo enable row level security;
alter table public.veiculo_modelos_catalogo enable row level security;

drop policy if exists "Catalogo de marcas visivel para todos" on public.veiculo_marcas_catalogo;
create policy "Catalogo de marcas visivel para todos"
on public.veiculo_marcas_catalogo
for select
to anon, authenticated
using (ativo = true);

drop policy if exists "Catalogo de modelos visivel para todos" on public.veiculo_modelos_catalogo;
create policy "Catalogo de modelos visivel para todos"
on public.veiculo_modelos_catalogo
for select
to anon, authenticated
using (ativo = true);

-- View pronta para buscas simples no frontend.
create or replace view public.vw_veiculo_catalogo as
select
  mo.id as modelo_id,
  ma.id as marca_id,
  ma.nome as marca,
  mo.nome as modelo,
  mo.tipo
from public.veiculo_modelos_catalogo mo
join public.veiculo_marcas_catalogo ma on ma.id = mo.marca_id
where ma.ativo = true
  and mo.ativo = true
order by ma.nome, mo.nome;

commit;

-- Exemplos de consulta:
-- Buscar marcas:
-- select id, nome from public.veiculo_marcas_catalogo where ativo = true order by nome;
--
-- Buscar modelos de uma marca:
-- select mo.id, mo.nome, mo.tipo
-- from public.veiculo_modelos_catalogo mo
-- join public.veiculo_marcas_catalogo ma on ma.id = mo.marca_id
-- where ma.nome = 'Fiat'
-- order by mo.nome;
--
-- Buscar por texto:
-- select * from public.vw_veiculo_catalogo
-- where marca ilike '%fiat%' or modelo ilike '%strada%'
-- limit 20;
