const DASH={userId:null,orcamentos:[],caixa:[]};
function norm(v){const p=String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();return['premium','basico','gestao'].includes(p)?'premium':p}
function moeda(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function html(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function val(id){return document.getElementById(id)?.value||''}
function set(id,v){const e=document.getElementById(id);if(e)e.textContent=String(v)}
function iso(d){return d.toISOString().slice(0,10)}
function dataBR(v){if(!v)return'-';const d=new Date(String(v).includes('T')?v:String(v)+'T00:00:00');return Number.isNaN(d.getTime())?'-':d.toLocaleDateString('pt-BR')}
function status(v){return String(v||'pendente').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim()}
function mesChave(v){const d=new Date(String(v||'').includes('T')?v:String(v||'')+'T00:00:00');if(Number.isNaN(d.getTime()))return'';return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function mesLabel(k){const [a,m]=String(k||'').split('-');return m&&a?`${m}/${String(a).slice(2)}`:'-'}
function parseItens(itens){if(Array.isArray(itens))return itens;if(typeof itens==='string'){try{const j=JSON.parse(itens);return Array.isArray(j)?j:[]}catch(_){return[]}}return[]}
function numero(v){return Number(v||0)||0}
function itemSubtotal(i){return numero(i.subtotal??i.total) || numero(i.valor??i.valor_unitario) * numero(i.qtd??i.quantidade??1)}
function setHTML(id,htmlText){const e=document.getElementById(id);if(e)e.innerHTML=htmlText}
async function iniciarDashboardFS(){try{const{data:{session}}=await _supabase.auth.getSession();if(!session?.user?.id){location.href='/index.html?login=1';return}DASH.userId=session.user.id;if(norm(localStorage.getItem('usuario_plano')||'gratis')!=='premium'){alert('Relatórios são recurso Premium.');location.href='/planos.html#assinar-plano-premium';return}const hoje=new Date(),ini=new Date();ini.setDate(hoje.getDate()-90);document.getElementById('dash-inicio').value=iso(ini);document.getElementById('dash-fim').value=iso(hoje);await carregarDashboardFS()}catch(e){console.error(e)}}
async function carregarDashboardFS(){const i=val('dash-inicio'),f=val('dash-fim');setHTML('resumo-relatorio','Carregando dados...');const[orc,caixa]=await Promise.all([buscarOrcamentos(i,f),buscarCaixa(i,f)]);DASH.orcamentos=orc;DASH.caixa=caixa;renderMetricas();renderGraficoMensal();renderRankings();renderResumoTexto();renderTabelas()}
async function buscarOrcamentos(i,f){let q=_supabase.from('orcamentos').select('*').eq('usuario_id',DASH.userId).order('criado_em',{ascending:false}).limit(1000);if(i)q=q.gte('criado_em',i);if(f)q=q.lte('criado_em',f+'T23:59:59');const{data,error}=await q;if(error){console.warn(error);return[]}return data||[]}
async function buscarCaixa(i,f){let q=_supabase.from('fluxo_caixa').select('*').eq('user_id',DASH.userId).order('data_movimento',{ascending:false}).limit(1000);if(i)q=q.gte('data_movimento',i);if(f)q=q.lte('data_movimento',f);const{data,error}=await q;if(error){console.warn(error);return[]}return data||[]}
function resumoDados(){const aprov=DASH.orcamentos.filter(o=>status(o.status)==='aprovado'),rec=DASH.orcamentos.filter(o=>status(o.status)==='recusado'),pend=DASH.orcamentos.filter(o=>!['aprovado','recusado'].includes(status(o.status)));const entradas=DASH.caixa.filter(c=>c.tipo==='entrada').reduce((s,c)=>s+Number(c.valor||0),0),saidas=DASH.caixa.filter(c=>c.tipo==='saida').reduce((s,c)=>s+Number(c.valor||0),0);const valorAprovado=aprov.reduce((s,o)=>s+Number(o.total||0),0);const totalDecisao=aprov.length+rec.length;return{aprov,rec,pend,entradas,saidas,valorAprovado,totalDecisao,taxa:totalDecisao?Math.round(aprov.length/totalDecisao*100):0,ticket:aprov.length?valorAprovado/aprov.length:0}}
function renderMetricas(){const r=resumoDados();set('m-orcamentos',DASH.orcamentos.length);set('m-pendentes',r.pend.length);set('m-aprovados',r.aprov.length);set('m-recusados',r.rec.length);set('m-taxa',r.taxa+'%');set('m-total-aprovado',moeda(r.valorAprovado));set('m-ticket',moeda(r.ticket));set('m-entradas',moeda(r.entradas));set('m-saidas',moeda(r.saidas));set('m-saldo',moeda(r.entradas-r.saidas))}
function renderGraficoMensal(){const box=document.getElementById('grafico-mensal');if(!box)return;const aprov=DASH.orcamentos.filter(o=>status(o.status)==='aprovado');const mapa={};aprov.forEach(o=>{const k=mesChave(o.criado_em||o.created_at);if(k)mapa[k]=(mapa[k]||0)+Number(o.total||0)});const lista=Object.entries(mapa).sort((a,b)=>a[0].localeCompare(b[0]));if(!lista.length){box.innerHTML='<div class="empty">Nenhum valor aprovado no período.</div>';return}const max=Math.max(...lista.map(x=>x[1]),1);box.innerHTML=lista.map(([k,v])=>`<div class="bar-row"><div class="bar-label">${html(mesLabel(k))}</div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(3,Math.round(v/max*100))}%"></div></div><div class="bar-value">${moeda(v)}</div></div>`).join('')}
function agruparItens(tipo){const mapa={};DASH.orcamentos.forEach(o=>{parseItens(o.itens).forEach(i=>{const isMao=(i.tipo||'')==='mao_obra';if((tipo==='mao_obra'&&!isMao)||(tipo==='produto'&&isMao))return;const desc=String(i.descricao||i.nome||'Item sem descrição').trim();const chave=desc.toLowerCase();if(!mapa[chave])mapa[chave]={descricao:desc,qtd:0,valor:0,usos:0};mapa[chave].qtd+=numero(i.qtd??i.quantidade??1);mapa[chave].valor+=itemSubtotal(i);mapa[chave].usos+=1})});return Object.values(mapa).sort((a,b)=>b.valor-a.valor||b.usos-a.usos).slice(0,8)}
function renderRanking(id,lista){const box=document.getElementById(id);if(!box)return;if(!lista.length){box.innerHTML='<div class="empty">Sem dados suficientes no período.</div>';return}box.innerHTML=lista.map((i,idx)=>`<div class="rank-item"><div><strong>${idx+1}. ${html(i.descricao)}</strong><small>${i.usos} uso(s) • qtd ${Number(i.qtd||0).toLocaleString('pt-BR')}</small></div><div><strong>${moeda(i.valor)}</strong></div></div>`).join('')}
function renderRankings(){renderRanking('ranking-mao-obra',agruparItens('mao_obra'));renderRanking('ranking-produtos',agruparItens('produto'))}
function renderResumoTexto(){const r=resumoDados();let texto='';if(!DASH.orcamentos.length&&!DASH.caixa.length){texto='Ainda não há dados suficientes neste período. Crie orçamentos, envie links e registre vendas no caixa para alimentar os relatórios.'}else if(r.aprov.length){texto=`No período, ${r.aprov.length} orçamento(s) foram aprovados, somando ${moeda(r.valorAprovado)}. O ticket médio aprovado ficou em ${moeda(r.ticket)} e a taxa de aprovação está em ${r.taxa}%.`}else{texto=`Foram criados ${DASH.orcamentos.length} orçamento(s), mas nenhum aprovado no período selecionado. O foco agora é acompanhar pendentes e reenviar propostas pelo WhatsApp.`}setHTML('resumo-relatorio',html(texto))}
function renderTabelas(){const orc=document.getElementById('lista-orcamentos-relatorio'),cx=document.getElementById('lista-caixa-relatorio');if(orc)orc.innerHTML=DASH.orcamentos.length?`<table class="table"><thead><tr><th>Data</th><th>Cliente</th><th>Status</th><th>Total</th></tr></thead><tbody>${DASH.orcamentos.slice(0,20).map(o=>`<tr><td>${dataBR(o.criado_em||o.created_at)}</td><td>${html(o.cliente_nome||'-')}</td><td><span class="status">${html(o.status||'pendente')}</span></td><td>${moeda(o.total)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhum orçamento no período.</div>';if(cx)cx.innerHTML=DASH.caixa.length?`<table class="table"><thead><tr><th>Data</th><th>Tipo</th><th>Descrição</th><th>Valor</th></tr></thead><tbody>${DASH.caixa.slice(0,20).map(c=>`<tr><td>${dataBR(c.data_movimento)}</td><td>${html(c.tipo)}</td><td>${html(c.descricao||'-')}</td><td>${moeda(c.valor)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhum lançamento no período.</div>'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',iniciarDashboardFS);else iniciarDashboardFS();window.carregarDashboardFS=carregarDashboardFS;
