const CX={userId:null,lista:[]};
function moeda(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}function html(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}function normalizar(v){const p=String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();return ['premium','basico','gestao'].includes(p)?'premium':p}function iso(d){return d.toISOString().slice(0,10)}function val(id){return document.getElementById(id)?.value?.trim()||''}function set(id,v){const e=document.getElementById(id);if(e)e.textContent=String(v)}function setVal(id,v){const e=document.getElementById(id);if(e)e.value=v??''}function dataBR(v){if(!v)return'-';const d=new Date(String(v)+'T00:00:00');return Number.isNaN(d.getTime())?'-':d.toLocaleDateString('pt-BR')}function msg(t,tipo='ok'){const e=document.getElementById('cx-msg');if(!e)return;e.textContent=t||'';e.className=t?'msg '+tipo:'msg'}
async function initFluxoCaixa(){try{const{data:{session}}=await _supabase.auth.getSession();if(!session?.user?.id){location.href='/index.html?login=1';return}CX.userId=session.user.id;const plano=normalizar(localStorage.getItem('usuario_plano')||'gratis');if(plano!=='premium'){alert('Fluxo de caixa é recurso Premium.');location.href='/planos.html#assinar-plano-premium';return}datasPadrao();document.getElementById('form-caixa')?.addEventListener('submit',salvarLancamento);document.getElementById('card-form-caixa')?.addEventListener('click',e=>{if(e.target?.id==='card-form-caixa')ocultarFormularioCaixa()});document.addEventListener('keydown',e=>{if(e.key==='Escape')ocultarFormularioCaixa()});await carregarFluxoCaixa()}catch(e){console.error(e)}}
function datasPadrao(){const f=new Date(),i=new Date();i.setDate(f.getDate()-30);if(!val('cx-inicio'))setVal('cx-inicio',iso(i));if(!val('cx-fim'))setVal('cx-fim',iso(f));if(!val('cx-data'))setVal('cx-data',iso(f))}
function mostrarFormularioCaixa(){const m=document.getElementById('card-form-caixa');if(!m)return;m.classList.add('ativo');setVal('cx-data',iso(new Date()));msg('');setTimeout(()=>document.getElementById('cx-valor')?.focus(),120)}function ocultarFormularioCaixa(){const m=document.getElementById('card-form-caixa');if(!m)return;m.classList.remove('ativo');document.getElementById('form-caixa')?.reset();setVal('cx-data',iso(new Date()));setVal('cx-tipo','entrada');setVal('cx-forma','pix');msg('')}
async function salvarLancamento(e){e.preventDefault();const valor=Number(val('cx-valor')||0);if(valor<=0)return msg('Informe um valor maior que zero.','erro');const payload={user_id:CX.userId,tipo:val('cx-tipo')||'entrada',categoria:val('cx-categoria')||'Geral',descricao:val('cx-descricao')||'Lançamento manual',valor,data_movimento:val('cx-data')||iso(new Date()),forma_pagamento:val('cx-forma')||'outro',origem_tipo:'manual',observacoes:val('cx-observacoes')||null};const{error}=await _supabase.from('fluxo_caixa').insert(payload);if(error){console.error(error);return msg('Não foi possível salvar.','erro')}ocultarFormularioCaixa();await carregarFluxoCaixa()}
async function carregarFluxoCaixa(){let q=_supabase.from('fluxo_caixa').select('*').eq('user_id',CX.userId).order('data_movimento',{ascending:false}).order('created_at',{ascending:false});const i=val('cx-inicio'),f=val('cx-fim'),tipo=val('cx-filtro-tipo');if(i)q=q.gte('data_movimento',i);if(f)q=q.lte('data_movimento',f);if(tipo)q=q.eq('tipo',tipo);const{data,error}=await q;if(error){console.error(error);document.getElementById('cx-lista').innerHTML='<div class="empty">Erro ao carregar fluxo de caixa.</div>';return}CX.lista=data||[];renderResumo();renderLista()}
function renderResumo(){const ent=CX.lista.filter(x=>x.tipo==='entrada'),sai=CX.lista.filter(x=>x.tipo==='saida');const ve=ent.reduce((s,x)=>s+Number(x.valor||0),0),vs=sai.reduce((s,x)=>s+Number(x.valor||0),0);set('cx-entradas',moeda(ve));set('cx-saidas',moeda(vs));set('cx-saldo',moeda(ve-vs));set('cx-total',CX.lista.length)}
function renderLista(){const box=document.getElementById('cx-lista');if(!box)return;if(!CX.lista.length){box.innerHTML='<div class="empty">Nenhum lançamento no período.</div>';return}box.innerHTML=`<table class="table"><thead><tr><th>Data</th><th>Tipo</th><th>Categoria</th><th>Descrição</th><th>Forma</th><th>Valor</th></tr></thead><tbody>${CX.lista.map(x=>`<tr><td>${dataBR(x.data_movimento)}</td><td><span class="badge ${html(x.tipo)}">${html(x.tipo)}</span></td><td>${html(x.categoria||'-')}</td><td>${html(x.descricao||'-')}</td><td>${html(x.forma_pagamento||'-')}</td><td><strong>${moeda(x.valor)}</strong></td></tr>`).join('')}</tbody></table>`}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initFluxoCaixa);else initFluxoCaixa();window.carregarFluxoCaixa=carregarFluxoCaixa;window.mostrarFormularioCaixa=mostrarFormularioCaixa;window.ocultarFormularioCaixa=ocultarFormularioCaixa;
