/* FS Orçamentos - fluxo-caixa.js */
const CX={userId:null,lista:[]};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initFluxoCaixa);else initFluxoCaixa();
function moeda(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}function html(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}function iso(d){return d.toISOString().slice(0,10)}function val(id){return document.getElementById(id)?.value?.trim()||''}function set(id,v){const e=document.getElementById(id);if(e)e.textContent=String(v)}function dataBR(v){if(!v)return'-';const d=new Date(String(v)+'T00:00:00');return isNaN(d)?'-':d.toLocaleDateString('pt-BR')}function msg(t,ok=true){const e=document.getElementById('cx-msg');if(!e)return;e.textContent=t||'';e.className=t?'msg '+(ok?'ok':'erro'):'msg'}
async function initFluxoCaixa(){try{const{data:{session}}=await _supabase.auth.getSession();if(!session?.user?.id){location.href='/index.html?login=1';return}CX.userId=session.user.id;datasPadrao();document.getElementById('form-caixa')?.addEventListener('submit',salvarLancamento);await carregarFluxoCaixa()}catch(e){console.error(e)}}
function datasPadrao(){const f=new Date(),i=new Date();i.setDate(f.getDate()-30);if(!val('cx-inicio'))document.getElementById('cx-inicio').value=iso(i);if(!val('cx-fim'))document.getElementById('cx-fim').value=iso(f);if(!val('cx-data'))document.getElementById('cx-data').value=iso(f)}
function mostrarFormularioCaixa(){document.getElementById('card-form-caixa').style.display='block';document.getElementById('cx-data').value=iso(new Date())}function ocultarFormularioCaixa(){document.getElementById('card-form-caixa').style.display='none';document.getElementById('form-caixa')?.reset();document.getElementById('cx-data').value=iso(new Date());msg('')}
async function salvarLancamento(e){e.preventDefault();const valor=Number(val('cx-valor')||0);if(valor<=0)return msg('Informe um valor maior que zero.',false);const payload={user_id:CX.userId,tipo:val('cx-tipo')||'entrada',categoria:val('cx-categoria')||'Geral',descricao:val('cx-descricao')||'Lançamento manual',valor,data_movimento:val('cx-data')||iso(new Date()),forma_pagamento:val('cx-forma')||'outro',origem_tipo:'manual',observacoes:val('cx-observacoes')||null};const{error}=await _supabase.from('fluxo_caixa').insert(payload);if(error){console.error(error);return msg('Não foi possível salvar.',false)}msg('Lançamento salvo.');ocultarFormularioCaixa();await carregarFluxoCaixa()}
async function carregarFluxoCaixa(){let q=_supabase.from('fluxo_caixa').select('*').eq('user_id',CX.userId).order('data_movimento',{ascending:false}).order('created_at',{ascending:false});const i=val('cx-inicio'),f=val('cx-fim'),tipo=val('cx-filtro-tipo');if(i)q=q.gte('data_movimento',i);if(f)q=q.lte('data_movimento',f);if(tipo)q=q.eq('tipo',tipo);const{data,error}=await q;if(error){console.error(error);document.getElementById('cx-lista').innerHTML='<div class="vazio">Erro ao carregar fluxo de caixa.</div>';return}CX.lista=data||[];renderResumo();renderLista()}
function renderResumo(){const ent=CX.lista.filter(x=>x.tipo==='entrada');const sai=CX.lista.filter(x=>x.tipo==='saida');const ve=ent.reduce((s,x)=>s+Number(x.valor||0),0),vs=sai.reduce((s,x)=>s+Number(x.valor||0),0);set('cx-entradas',moeda(ve));set('cx-saidas',moeda(vs));set('cx-saldo',moeda(ve-vs));set('cx-total',CX.lista.length);set('cx-ticket',moeda(ent.length?ve/ent.length:0))}
function renderLista(){const box=document.getElementById('cx-lista');if(!CX.lista.length){box.innerHTML='<div class="vazio">Nenhum lançamento no período.</div>';return}box.innerHTML=`<table class="tab"><thead><tr><th>Data</th><th>Tipo</th><th>Categoria</th><th>Descrição</th><th>Forma</th><th>Valor</th><th></th></tr></thead><tbody>${CX.lista.map(x=>`<tr><td>${html(dataBR(x.data_movimento))}</td><td><span class="tipo ${html(x.tipo)}">${html(x.tipo)}</span></td><td>${html(x.categoria||'-')}</td><td><strong>${html(x.descricao||'-')}</strong><br><small>${html(x.observacoes||'')}</small></td><td>${html(x.forma_pagamento||'-')}</td><td><strong>${html(moeda(x.valor))}</strong></td><td><button class="btn" onclick="excluirLancamentoCaixa('${html(x.id)}')">Excluir</button></td></tr>`).join('')}</tbody></table>`}
async function excluirLancamentoCaixa(id){if(!confirm('Excluir este lançamento?'))return;const{error}=await _supabase.from('fluxo_caixa').delete().eq('id',id).eq('user_id',CX.userId);if(error)return alert('Não foi possível excluir.');await carregarFluxoCaixa()}
window.carregarFluxoCaixa=carregarFluxoCaixa;window.mostrarFormularioCaixa=mostrarFormularioCaixa;window.ocultarFormularioCaixa=ocultarFormularioCaixa;window.excluirLancamentoCaixa=excluirLancamentoCaixa;