/* FS Orçamentos - controle simples de saldo da OS */
(function(){
  let os=null,userId=null;
  const $=id=>document.getElementById(id);
  const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const idOS=()=>new URLSearchParams(location.search).get('id')||'';
  const num=v=>{const n=Number(v||0);return Number.isFinite(n)?n:0};
  function css(){if($('fs-os-saldo-css'))return;const s=document.createElement('style');s.id='fs-os-saldo-css';s.textContent='.fs-saldo{margin-top:12px;padding:10px;border:1px solid #e4d8cc;border-radius:8px;background:#fbf8f4;display:grid;gap:8px}.fs-saldo h3{margin:0;color:#2f211d;font-size:15px}.fs-saldo-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.fs-saldo-box{background:#fff;border:1px solid #e4d8cc;border-left:4px solid #ffc400;border-radius:7px;padding:8px}.fs-saldo-box span{display:block;color:#62554d;font-size:10px;font-weight:900;text-transform:uppercase}.fs-saldo-box strong{display:block;color:#2f211d;font-size:15px}.fs-saldo-form{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.fs-saldo-form label{display:grid;gap:4px;font-size:10px;font-weight:900;text-transform:uppercase;color:#2f211d}.fs-saldo-form input,.fs-saldo-form select{border:1px solid #d7ccc8;border-radius:5px;padding:8px}.fs-saldo button{min-height:34px;border-radius:7px;border:1px solid #ffc400;background:#3e2723;color:#ffc400;font-weight:900;padding:8px;cursor:pointer}@media(max-width:700px){.fs-saldo-grid,.fs-saldo-form{grid-template-columns:1fr 1fr}}@media(max-width:480px){.fs-saldo-grid,.fs-saldo-form{grid-template-columns:1fr}.fs-saldo button{width:100%}}';document.head.appendChild(s)}
  async function load(){if(!window._supabase&&window.inicializarSupabaseFS)window.inicializarSupabaseFS();const r=await _supabase.auth.getSession();userId=r.data.session?.user?.id;if(!userId||!idOS())return;const q=await _supabase.from('ordens_servico').select('id,valor_total,valor_entrada,valor_pago,saldo_restante,forma_pagamento,status_pagamento').eq('id',idOS()).eq('user_id',userId).maybeSingle();os=q.data}
  function calc(){const total=num($('fs-total').value),entrada=num($('fs-entrada').value);let pago=num($('fs-pago').value);if(entrada>pago)pago=entrada;if(total>0&&pago>total)pago=total;const saldo=Math.max(total-pago,0);const status=total<=0?'pendente':pago<=0?'pendente':saldo>0?'parcial':'pago';$('fs-box-total').textContent=money(total);$('fs-box-pago').textContent=money(pago);$('fs-box-saldo').textContent=money(saldo);$('fs-box-status').textContent=status;return{total,entrada,pago,saldo,status}}
  function alvo(){return [...document.querySelectorAll('.card,section,article')].find(e=>/pagamento|valores|financeiro/i.test(e.textContent||''))||document.querySelector('main')||document.body}
  function ui(){if(!os||$('fs-saldo'))return;const d=document.createElement('div');d.id='fs-saldo';d.className='fs-saldo';d.innerHTML='<h3>Controle de entrada e saldo</h3><div class="fs-saldo-grid"><div class="fs-saldo-box"><span>Total</span><strong id="fs-box-total"></strong></div><div class="fs-saldo-box"><span>Pago</span><strong id="fs-box-pago"></strong></div><div class="fs-saldo-box"><span>Saldo</span><strong id="fs-box-saldo"></strong></div><div class="fs-saldo-box"><span>Status</span><strong id="fs-box-status"></strong></div></div><div class="fs-saldo-form"><label>Total<input id="fs-total" type="number" step="0.01"></label><label>Entrada<input id="fs-entrada" type="number" step="0.01"></label><label>Total pago<input id="fs-pago" type="number" step="0.01"></label><label>Forma<select id="fs-forma"><option value="">Não informado</option><option value="pix">Pix</option><option value="dinheiro">Dinheiro</option><option value="cartao">Cartão</option><option value="outro">Outro</option></select></label></div><button type="button" id="fs-save-saldo">Salvar pagamento</button>' ;alvo().appendChild(d);$('fs-total').value=os.valor_total||0;$('fs-entrada').value=os.valor_entrada||0;$('fs-pago').value=os.valor_pago||0;$('fs-forma').value=os.forma_pagamento||'';['fs-total','fs-entrada','fs-pago'].forEach(id=>$(id).addEventListener('input',calc));$('fs-save-saldo').onclick=save;calc()}
  async function save(){const c=calc();const payload={valor_total:c.total,valor_entrada:c.entrada,valor_pago:c.pago,saldo_restante:c.saldo,status_pagamento:c.status,forma_pagamento:$('fs-forma').value||null};const r=await _supabase.from('ordens_servico').update(payload).eq('id',idOS()).eq('user_id',userId);if(r.error)return alert('Não foi possível salvar.');alert('Pagamento atualizado.');}
  async function init(){css();await load();ui()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,1200));else setTimeout(init,1200);
})();