import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.4";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const PRODUTOS:Record<string,any>={
  assinatura_essencial:{tipo:"assinatura",label:"Premium Essencial - 1 mês",valor:14.9,plano:"premium",nivel:"essencial",dias:30,creditos:15},
  assinatura_pro:{tipo:"assinatura",label:"Premium Pro - 1 mês",valor:29.9,plano:"premium",nivel:"pro",dias:30,creditos:30},
  creditos_20:{tipo:"creditos",label:"20 créditos Efex",valor:9.9,plano:"gratis",nivel:null,dias:0,creditos:20},
  creditos_50:{tipo:"creditos",label:"50 créditos Efex",valor:24.9,plano:"gratis",nivel:null,dias:0,creditos:50},
  creditos_100:{tipo:"creditos",label:"100 créditos Efex",valor:49.9,plano:"gratis",nivel:null,dias:0,creditos:100},
  creditos_200:{tipo:"creditos",label:"200 créditos Efex",valor:99.9,plano:"gratis",nivel:null,dias:0,creditos:200},
  creditos_400:{tipo:"creditos",label:"400 créditos Efex",valor:189.9,plano:"gratis",nivel:null,dias:0,creditos:400}
};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const env=(n:string)=>{const v=Deno.env.get(n);if(!v)throw new Error(`Secret ausente: ${n}`);return v};
function base64ToText(v:string){return new TextDecoder().decode(Uint8Array.from(atob(v),c=>c.charCodeAt(0)))}
function http(){const pem=base64ToText(env("EFI_CERT_KEY_PEM_BASE64")),cert=pem.match(/-----BEGIN CERTIFICATE-----[\s\S]*?-----END CERTIFICATE-----/)?.[0],key=pem.match(/-----BEGIN (?:RSA )?PRIVATE KEY-----[\s\S]*?-----END (?:RSA )?PRIVATE KEY-----/)?.[0];if(!cert||!key)throw new Error("Certificado Efí inválido.");return Deno.createHttpClient({cert,key})}
function base(){const e=(Deno.env.get("EFI_ENV")||"homologation").toLowerCase();return ["production","producao","produção","prod"].includes(e)?"https://pix.api.efipay.com.br":"https://pix-h.api.efipay.com.br"}
function txid(){return (`FS${Date.now()}${crypto.randomUUID().replace(/-/g,"").slice(0,16)}`).slice(0,35)}
async function token(c:Deno.HttpClient){const r=await fetch(base()+"/oauth/token",{method:"POST",client:c,headers:{Authorization:`Basic ${btoa(`${env("EFI_CLIENT_ID")}:${env("EFI_CLIENT_SECRET")}`)}`,"Content-Type":"application/json"},body:JSON.stringify({grant_type:"client_credentials"})});const t=await r.text();if(!r.ok)throw new Error("Erro ao autenticar na Efí: "+t);return JSON.parse(t).access_token}
serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({erro:"Método não permitido."},405);try{const auth=req.headers.get("Authorization");if(!auth)return json({erro:"Usuário não autenticado."},401);const url=env("SUPABASE_URL"),anon=env("SUPABASE_ANON_KEY"),service=env("SUPABASE_SERVICE_ROLE_KEY");const authClient=createClient(url,anon,{global:{headers:{Authorization:auth}}});const{data:u,error:ue}=await authClient.auth.getUser();if(ue||!u.user)return json({erro:"Sessão inválida."},401);const body=await req.json().catch(()=>({})),codigo=String(body.produto_codigo||"");const p=PRODUTOS[codigo];if(!p)return json({erro:"Produto comercial inválido."},400);const c=http(),access=await token(c),id=txid(),desc=`${p.label} FS Orçamentos`;const cob=await fetch(`${base()}/v2/cob/${id}`,{method:"PUT",client:c,headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify({calendario:{expiracao:3600},valor:{original:p.valor.toFixed(2)},chave:env("EFI_PIX_KEY"),solicitacaoPagador:desc.slice(0,140)})});const ct=await cob.text();if(!cob.ok)throw new Error("Erro ao criar cobrança Pix: "+ct);const cobranca=JSON.parse(ct),locId=cobranca?.loc?.id;if(!locId)throw new Error("A Efí não retornou loc.id.");const qrRes=await fetch(`${base()}/v2/loc/${locId}/qrcode`,{method:"GET",client:c,headers:{Authorization:`Bearer ${access}`}}),qt=await qrRes.text();if(!qrRes.ok)throw new Error("Erro ao gerar QR Code: "+qt);const qr=JSON.parse(qt),admin=createClient(url,service),expira=new Date(Date.now()+3600000).toISOString();const{data:pag,error:pe}=await admin.from("pagamentos_pix").insert({usuario_id:u.user.id,plano:p.plano,periodo:p.tipo==="assinatura"?"mensal":"avulso",dias:p.dias,valor:p.valor,status:"pendente",gateway:"efi",txid:id,efi_id:String(locId),pix_copia_cola:qr?.qrcode||null,qr_code:qr?.imagemQrcode||null,link_pagamento:qr?.linkVisualizacao||null,expira_em:expira,produto_tipo:p.tipo,produto_codigo:codigo,creditos:p.creditos}).select("id").single();if(pe)throw new Error("Pix gerado, mas falhou ao salvar: "+pe.message);return json({sucesso:true,pagamento_id:pag.id,produto_codigo:codigo,produto_tipo:p.tipo,label:p.label,valor:p.valor,creditos:p.creditos,txid:id,expira_em:expira,pix_copia_cola:qr?.qrcode||"",qr_code:qr?.imagemQrcode||"",link_pagamento:qr?.linkVisualizacao||""})}catch(e){console.error(e);return json({erro:e instanceof Error?e.message:"Erro interno ao gerar Pix."},500)}});